#java -jar myApp.jar --spring.profiles.active=dev
server:
  port: 8088

spring:
  profiles: dev
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.0.50:3306/pjt?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&useUnicode=true
      username: pjt
      password: pjt6^
  jpa:
      hibernate:
        ddl-auto: update
        #ddl-auto: validate
        generate-ddl: true
        show-sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 100MB

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
